### ISSUE TITLE
I think this project is abandoned! right?

### ISSUE THREAD

**Issue by cdsuperstar** [laravelbook/ardent#275]
Wondering....

**Comment by igorsantos07** [comment]
Not completely right!
I'm the only maintainer here, as the original one abandoned it. Luckily I could take over before he vanish, but I cannot update the Packagist information for instance.
I had a couple of health issues since last year, and now I'm in the process of finishing my degree. On the other hand, I'm changing my jobs and I'll probably have some time to dedicate here as I'll be working from home during part of the week.

Again I'm sorry for all this trouble, but it's really something out of my control :(
